### ISSUE TITLE
What are the terms of use?

### ISSUE THREAD

**Issue by fmahnke** [bigdunka/alttptracker#12]
Hi, thank you for making this. I'm new to ALTTP randomizer and am using it for entrance tracking.

What are the terms of use for the code? I'm making some changes to save the tracker state to local storage so it'll survive a reload. I'm unsure whether I can put my changes on github since there's no license with the code.

**Comment by fmahnke** [comment]
I've made some changes and would like to put my fork on github, but I don't want to violate your copyright. Can you tell me if I'm free to distribute them, and would you be willing to add a license file to the repository if so?

**Comment by bigdunka** [comment]
(Sorry for the delayed response, I rarely check this)

You are free to distribute openly! I have no license. Fork and distribute all you want.
