### ISSUE TITLE
So we forced to use the web based version due to this fake git hub?

### ISSUE THREAD

**Issue by Moltresrider** [bigdunka/alttptracker#13]
Your website led me here to download the local version but there is no local version on here. No exe, zip, rar, or 7z of any kind with an executable. 

The direct link on the website is also fake. It is just a bunch of HTML files and files my computer does not recognize.

**Comment by Gnatzelle** [comment]
@Moltresrider There is a "tracker.zip" in the Repo...extract this and then open the "index.html" == Offline Copy on your PC > Problem solved

And in the future it would be nice to think before writing bullshit or insulting people because you don't get it...

**Comment by bigdunka** [comment]
> Your website led me here to download the local version but there is no local version on here. No exe, zip, rar, or 7z of any kind with an executable.
> 
> The direct link on the website is also fake. It is just a bunch of HTML files and files my computer does not recognize.

Please have basic understanding of things before spouting nonsense
