### ISSUE TITLE
Feature Request: Direct Links.

### ISSUE THREAD

**Issue by skyscooby** [bigdunka/alttptracker#4]
Is it possible (or does it already exist?) endpoints similar to the alttpr itself..  such that the page loads and imports the seed data automatically? Like: https://alttptracker.dunka.net/seed/ObGbXdJZvP

It might be possible then to add a feature to the SahasrahBot to generate these quicklinks for players in it's response. Or even add a feature on the ALttpR site itself.

**Comment by bigdunka** [comment]
If you want to import the seed data, you can use the Import Flags option at the top right of the tracker. It loads about 90% of the flags, but there are some customizer flags that it will not bring in. There isn't much we can do about that, the data doesn't exist in the scope to import.
