### ISSUE TITLE
UX Improvement: Crystals / Pendants

### ISSUE THREAD

**Issue by skyscooby** [bigdunka/alttptracker#5]
Having used your tracker several dozen times now I can say it's great but.. it takes way longer than it needs to to adjust the Crystals and Pendants when looking at the map.. 

Crystals (the most common) take 3 clicks for blue and 4 clicks for red. So to set those alone takes 23 mouse clicks + 5 for the pendants for a total of 28 mouse clicks to configure the awards each game.

One simple improvement would be to re-order the items in order of # of occurrences 
(Blue Crystal, Red Crystal, Blue/Red Pendant, Green Pendant) this reduces the clicks required to 9 for crystals and 10 for the pendants (19 clicks).

We could also consider completely removing the '?' option and setting all the initial values to Blue Crystals since there the most of them. User just identifies the red crystals and pendants and could have as few as 8 clicks to setup the awards that are not blue crystals. (perhaps make this an optional when launching the tracker as not to confuse existing users).

In a game that is about racing / time usually.. it is nice to optimise the workflow (hence the idea of auto tracking in the first place).

**Comment by skyscooby** [comment]
I just noticed it's possible to go in both directions 'left vs right click' .. so really this could be largely improved with a simple
"Start the tracker with blue crystals selected Y/N" type option.

**Comment by bigdunka** [comment]
This is one of those options that I doubt that we'll implement. TBH, you get used to left click / right click. The most any option should ever take is 3, if maps are also live. I think the point is to be consistent, and any mode with wild maps, you wouldn't want any starting values in there. It would be a pain to have to change every time the tracker loads.
